name: DAST 

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    name: DAST
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create Output folder
        run: mkdir ${{ github.workspace }}/output_fold
      - name: Change dir owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Run DAST-CLI command
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        run: |
           docker run --pull=always \
           -v ${{ runner.temp }}/output:/tmp \
           -e CX_APIKEY="$CX_APIKEY" \
           checkmarx/dast:latest \
           web \
           scan \
           --config="./security_tweets.yaml" \
           --environment-id=e2f832dc-7ff0-4316-8114-62e794ae7d36 \
           --base-url=https://ind.ast.checkmarx.net \
           --output=/tmp
           
      - name: Reclaim output directory
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_fold
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ${{ github.workspace }}/output_fold
